#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_LENGTH 1000

#define EXECV_SIZE 6
#define SYSTEM_CLOCK_ID_INDEX 0
#define RESOURCE_DESCRIPTOR_ID_INDEX 1
#define MESSAGE_QUEUE_ID_INDEX 2
#define PID_ID_INDEX 3

#define IPC_KEY_PATHNAME "."
#define SYSTEM_CLOCK_KEY_ID 0
#define RESOURCE_DESRIPTOR_KEY_ID 1
#define MESSAGE_QUEUE_KEY_ID 2

#define TIMEOUT 5
#define TOTAL_PROCESSES 40
#define MAX_PROCESSES 18
#define MAX_RESOURCES 20

#define MAX_PROCESSES 18

#endif
